name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.7.1
    - name: Install chromedriver
      run: sudo apt-get -yqq install chromium-chromedriver
    - name: Install Yarn dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Install Ruby dependencies
      run: bundle install
    - name: Prepare database
      run: bundle exec rails db:prepare
    - name: Run tests
      run: bundle exec rake
    - name: Run system tests
      run: bundle exec rake test:system
